"""create sources table

Revision ID: 9c769d0f3347
Revises: 
Create Date: 2026-07-10 07:32:26.515563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c769d0f3347'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sources',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('rss_url', sa.Text(), nullable=True),
    sa.Column('api_url', sa.Text(), nullable=True),
    sa.Column('source_type', sa.Enum('NEWS', 'AGENCY', 'REGIONAL', 'ALTERNATIVE', 'PRIMARY_SOURCE', 'NGO', 'COMPANY', 'ACADEMIC', 'THINK_TANK', 'SIGNAL', name='source_type'), nullable=False),
    sa.Column('coverage_scope', sa.Enum('LOCAL', 'REGIONAL', 'NATIONAL', 'INTERNATIONAL', 'GLOBAL', name='coverage_scope'), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('ownership', sa.Text(), nullable=True),
    sa.Column('funding_model', sa.String(length=100), nullable=True),
    sa.Column('paywall', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('transparency_level', sa.Integer(), nullable=True),
    sa.Column('correction_policy', sa.Text(), nullable=True),
    sa.Column('primary_source_usage', sa.Integer(), nullable=True),
    sa.Column('priority_tier', sa.Integer(), server_default=sa.text('3'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('primary_source_usage BETWEEN 0 AND 100', name='ck_sources_primary_source_usage_range'),
    sa.CheckConstraint('priority_tier BETWEEN 1 AND 4', name='ck_sources_priority_tier_range'),
    sa.CheckConstraint('transparency_level BETWEEN 0 AND 100', name='ck_sources_transparency_level_range'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sources_slug'), 'sources', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(op.f("ix_sources_slug"), table_name="sources")
    op.drop_table("sources")

    sa.Enum(name="coverage_scope").drop(
        op.get_bind(),
        checkfirst=True,
    )
    sa.Enum(name="source_type").drop(
        op.get_bind(),
        checkfirst=True,
    )
