"""add normalized source name

Revision ID: ed6e86f99520
Revises: 9c769d0f3347
Create Date: 2026-07-11 19:00:24.326937

"""
from typing import Sequence, Union
import unicodedata

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed6e86f99520'
down_revision: Union[str, Sequence[str], None] = '9c769d0f3347'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('sources', sa.Column('normalized_name', sa.String(length=255), nullable=True))

    connection = op.get_bind()
    sources = connection.execute(sa.text("SELECT id, name FROM sources"))
    for source_id, name in sources:
        normalized_name = unicodedata.normalize("NFKC", name)
        normalized_name = " ".join(normalized_name.strip().split()).casefold()
        connection.execute(
            sa.text(
                "UPDATE sources SET normalized_name = :normalized_name WHERE id = :id"
            ),
            {"id": source_id, "normalized_name": normalized_name},
        )

    op.alter_column(
        'sources',
        'normalized_name',
        existing_type=sa.String(length=255),
        nullable=False,
    )
    op.create_index(op.f('ix_sources_normalized_name'), 'sources', ['normalized_name'], unique=True)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sources_normalized_name'), table_name='sources')
    op.drop_column('sources', 'normalized_name')
    # ### end Alembic commands ###
