from enum import Enum


class PublicationFrequency(str, Enum):
    CONTINUOUS = "CONTINUOUS"
    MULTIPLE_DAILY = "MULTIPLE_DAILY"
    DAILY = "DAILY"
    MULTIPLE_WEEKLY = "MULTIPLE_WEEKLY"
    WEEKLY = "WEEKLY"
    BIWEEKLY = "BIWEEKLY"
    MONTHLY = "MONTHLY"
    BIMONTHLY = "BIMONTHLY"
    QUARTERLY = "QUARTERLY"
    SEMIANNUAL = "SEMIANNUAL"
    ANNUAL = "ANNUAL"
    IRREGULAR = "IRREGULAR"
    OTHER = "OTHER"
