from enum import Enum


class PublicationFormat(str, Enum):
    DAILY_NEWSPAPER = "DAILY_NEWSPAPER"
    WEEKLY_NEWSPAPER = "WEEKLY_NEWSPAPER"
    SUNDAY_NEWSPAPER = "SUNDAY_NEWSPAPER"
    MAGAZINE = "MAGAZINE"
    NEWS_MAGAZINE = "NEWS_MAGAZINE"
    TRADE_MAGAZINE = "TRADE_MAGAZINE"
    RADIO = "RADIO"
    TELEVISION = "TELEVISION"
    ONLINE_NEWS = "ONLINE_NEWS"
    NEWS_AGENCY = "NEWS_AGENCY"
    NEWSLETTER = "NEWSLETTER"
    PODCAST = "PODCAST"
    OTHER = "OTHER"
