from enum import Enum


class ReachMetricType(str, Enum):
    PRINT_SOLD_CIRCULATION = "PRINT_SOLD_CIRCULATION"
    PRINT_DISTRIBUTION = "PRINT_DISTRIBUTION"
    EPAPER_CIRCULATION = "EPAPER_CIRCULATION"
    DIGITAL_UNIQUE_USERS = "DIGITAL_UNIQUE_USERS"
    DIGITAL_VISITS = "DIGITAL_VISITS"
    PAID_DIGITAL_SUBSCRIBERS = "PAID_DIGITAL_SUBSCRIBERS"
    SOCIAL_FOLLOWERS = "SOCIAL_FOLLOWERS"
    VIDEO_VIEWS = "VIDEO_VIEWS"
    OTHER = "OTHER"
