from enum import Enum


class SourceClassificationKind(str, Enum):
    POLITICAL_ORIENTATION = "POLITICAL_ORIENTATION"
    RADICALITY = "RADICALITY"


class PoliticalOrientation(str, Enum):
    LEFT = "LEFT"
    CENTER_LEFT = "CENTER_LEFT"
    LIBERAL = "LIBERAL"
    CENTER = "CENTER"
    ECONOMIC_LIBERAL = "ECONOMIC_LIBERAL"
    CENTER_RIGHT = "CENTER_RIGHT"
    CONSERVATIVE = "CONSERVATIVE"
    LIBERAL_CONSERVATIVE = "LIBERAL_CONSERVATIVE"
    RIGHT_CONSERVATIVE = "RIGHT_CONSERVATIVE"
    RIGHT = "RIGHT"
    MIXED = "MIXED"
    UNCLASSIFIED = "UNCLASSIFIED"


class SourceRadicality(str, Enum):
    MAINSTREAM = "MAINSTREAM"
    RADICAL = "RADICAL"
    EXTREMIST_CLASSIFIED = "EXTREMIST_CLASSIFIED"
    UNCLASSIFIED = "UNCLASSIFIED"
